modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0"

[[mods]]
modId = "itemcounter"
version = "${version}"
displayName = "Potion Abilities"
authors = "To_Craft"
description = '''
This adds a custom Item Counter to the game.
'''

[[dependencies.itemcounter]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.itemcounter]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"
